version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: qwe123
      MYSQL_DATABASE: travel

  jenkins-server:
    image: jenkins/jenkins:lts
    volumes:
      - ./jenkins:/var/jenkins_home
    ports:
      - 8080:8080