spring:
  profiles:
    active: jwt,oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j9d210.p.ssafy.io:3306/travel
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true # 콘솔창에 sql 출력
    properties:
      hibernate:
        format_sql: true # sql 예쁘게 출력
        default_batch_fetch_size: 1000 # 일대다 컬렉션 조회 시 성능 최적화 : 100 ~ 1000 권장
        jdbc:
          time_zone: Asia/Seoul

  servlet:
    multipart:
      max-file-size: 20MB # 파일 업로드 요청 시 하나의 파일 크기를 10MB 제한
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일 크기합을 100MB 제한


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.SQL: debug

  kafka:
    consumer:
      bootstrap-servers: localhost:9090
      group-id: my_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

feign:
  client:
    config:
      default: # 전역 처리
        # 타임아웃 제한 시간
        connectTimeout: 5000
        readTimeout: 5000

http:
  auth-token-header:
    name: Authorization

  auth-token: ssafy_d210_bankserver